keboola_docker_sandbox:
    path:     /sandbox
    defaults: { _controller: KeboolaDockerBundle:Api:sandbox }
    methods:  [POST]

keboola_docker_component_input:
    path:     /{component}/input
    defaults: { _controller: KeboolaDockerBundle:Api:input }
    methods:  [POST]

keboola_docker_component_run:
    path:     /{component}/run
    defaults: { _controller: KeboolaDockerBundle:Api:run }
    methods:  [POST]

keboola_docker_component_tag_run:
    path:     /{component}/run/tag/{tag}
    defaults: { _controller: KeboolaDockerBundle:Api:runTag }
    methods:  [POST]

# override default syrup action run
keboola_docker_disabled_run:
    path:     /run
    defaults: { _controller: KeboolaDockerBundle:Api:disabled }
    methods:  [POST]

keboola_docker_component_dry_run:
    path:     /{component}/dry-run
    defaults: { _controller: KeboolaDockerBundle:Api:dryRun }
    methods:  [POST]

keboola_docker_encrypt:
    path:     /{component}/encrypt
    defaults:
      _controller: KeboolaDockerBundle:Public:encrypt
    methods:  [POST]

keboola_docker_encrypt_config:
    path:     /{component}/configs/encrypt
    defaults:
      _controller: KeboolaDockerBundle:Api:encryptConfig
    methods:  [POST]

keboola_docker_save_config:
    path:     /{component}/configs/{configId}
    defaults:
      _controller: KeboolaDockerBundle:Api:saveConfig
    methods:  [PUT]

# run sync actions
keboola_docker_sync_action:
    path:     /{component}/action/{action}
    defaults:
      _controller: KeboolaDockerBundle:Action:process
    methods:  [POST]
