services:
    syrup.components:
        class: Keboola\DockerBundle\Service\ComponentsService
        arguments: ["@syrup.storage_api"]

    syrup.job_executor:
        class: Keboola\DockerBundle\Job\Executor
        arguments:
          - "@logger"
          - "@docker_bundle.runner"
          - "@docker_bundle.object_encryptor_factory"
          - "@syrup.components"
          - "%storage_api.url%"

    syrup.job_factory:
        class: Keboola\DockerBundle\Job\Metadata\JobFactory
        arguments: ["%app_name%", "@docker_bundle.object_encryptor_factory", "@syrup.storage_api"]

    docker_bundle.loggers:
        class: Keboola\DockerBundle\Service\LoggersService
        arguments: ["@logger", "@docker_bundle.monolog.logger", "@docker_bundle.monolog.sapi_handler"]

    docker_bundle.monolog.logger:
        class: Keboola\DockerBundle\Monolog\ContainerLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: container }

    syrup.monolog.sapi_handler:
        class: Keboola\DockerBundle\Monolog\Handler\StorageApiHandler
        arguments: ["%app_name%", "@syrup.storage_api"]

    docker_bundle.monolog.sapi_handler:
        class: Keboola\DockerBundle\Monolog\Handler\StorageApiHandler
        arguments: ["%app_name%", "@syrup.storage_api"]

    docker_bundle.runner:
        class: Keboola\DockerBundle\Service\Runner
        arguments:
          - "@docker_bundle.object_encryptor_factory"
          - "@syrup.storage_api"
          - "@docker_bundle.loggers"
          - "@syrup.elasticsearch.current_component_job_mapper"
          - "%oauth_api.url%"
          - "%instance_limits%"

    docker_bundle.object_encryptor_factory:
        class: Keboola\ObjectEncryptor\ObjectEncryptorFactory
        arguments: ["%kms_key_id%", "%kms_key_region%", "%encryption_key%", "%encryption_key%"]

    syrup.storage_api:
        class: Keboola\DockerBundle\Service\StorageApiService
        arguments: ["@request_stack", "%storage_api.url%"]
