services:

    syrup.components:
        class: Keboola\DockerBundle\Service\ComponentsService
        arguments: [@syrup.storage_api]

    syrup.encryption.component_wrapper:
        class: Keboola\DockerBundle\Encryption\ComponentWrapper
        arguments: [%encryption_key%]
        tags:
            - { name: syrup.encryption.wrapper }

    syrup.encryption.component_project_wrapper:
        class: Keboola\DockerBundle\Encryption\ComponentProjectWrapper
        arguments: [%encryption_key%]
        tags:
            - { name: syrup.encryption.wrapper }

    syrup.job_executor:
        class: Keboola\DockerBundle\Job\Executor
        arguments: [@logger, @syrup.temp, @syrup.object_encryptor, @syrup.components, @syrup.encryption.component_wrapper, @syrup.encryption.component_project_wrapper, @docker.logger]

    syrup.job_factory:
        class: Keboola\DockerBundle\Job\Metadata\JobFactory
        arguments: [%app_name%, @syrup.object_encryptor, @syrup.storage_api]

    docker.logger:
        class: Keboola\DockerBundle\Monolog\ContainerLogger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: container }