FORMAT: 1A

# Docker
Docker is a Keboola service, that runs Docker images.

# Group Run

Run a configuration in an image.

## Create a job [/{image}/run]

Create a job on a specified docker image.

+ Parameters
    + image (string) ... ID of the image

### Custom configuration [POST]
+ Request (application/json)
    + Headers
    
            X-StorageApi-Token: 123456
        
    + Body
    
            {
                "configData":  {
                    "storage": {
                        "input": [
                            {
                                "name": "orders",
                                "value": "in.c-main.orders"
                            },
                            {
                                "name": "customers",
                                "value": "in.c-main.customers"
                            }
                        ],
                        "output": [
                            {
                                "name": "result",
                                "value": "out.c-main.next-order"
                            }
                        ]
                    },
                    "parameters": {
                        "values": [
                            {
                                "name": "minimum-orders",
                                "value": "10"
                            },
                            {
                                "name": "period",
                                "value": "12"
                            }
                        ],
                        "script": null
                    }
                } 
            }

+ Response 202 (application/json)

        {
            "id": "67121676",
            "url": "https://syrup.keboola.com/queue/job/67121676",
            "status": "waiting"
        }
    
### Stored configuration [POST]
+ Request (application/json)
    + Headers
    
            X-StorageApi-Token: 123456

    + Body
    
            {
                "config": "next-order-1"
            }

+ Response 202 (application/json)

        {
            "id": "67121676",
            "url": "https://syrup.keboola.com/queue/job/67121676",
            "status": "waiting"
        }


## Prepare data[/prepare?format={format}]

This job will prepare the `\data\` folder including serialized configuration file in the given format. Then it will put the `\data\` folder in a ZIP archive and upload it to your project in KBC Storage. The image itself will not be downloaded nor executed.

Note: only 50 first rows of each table will be exported.

+ Parameters
    + format (string) ... format of configuration file and file/table manifests `json` or `yaml`

### Custom configuration [POST]
+ Request (application/json)
    + Headers
    
            X-StorageApi-Token: 123456
        
    + Body
    
            {
                "configData":  {
                    "storage": {
                        "input": [
                            {
                                "name": "orders",
                                "value": "in.c-main.orders"
                            },
                            {
                                "name": "customers",
                                "value": "in.c-main.customers"
                            }
                        ],
                        "output": [
                            {
                                "name": "result",
                                "value": "out.c-main.next-order"
                            }
                        ]
                    },
                    "parameters": {
                        "values": [
                            {
                                "name": "minimum-orders",
                                "value": "10"
                            },
                            {
                                "name": "period",
                                "value": "12"
                            }
                        ],
                        "script": null
                    }
                } 
            }

+ Response 202 (application/json)

        {
            "id": "67121676",
            "url": "https://syrup.keboola.com/queue/job/67121676",
            "status": "waiting"
        }
