FORMAT: 1A

# Docker
Docker is a Keboola service, that runs Docker images.

# Group Run

Run a configuration on an image.

## Run an image [/{image}/run]

Run a job with all configuration in the request.

+ Parameters
    + image (string) ... ID of the image

### Create a job [POST]
+ Request (application/json)
    + Headers
    
            X-StorageApi-Token: 123456
        
    + Body
    
            {
                "configData":  {
                    "storage": {
                        "input": [
                            {
                                "name": "orders",
                                "value": "in.c-main.orders"
                            },
                            {
                                "name": "customers",
                                "value": "in.c-main.customers"
                            }
                        ],
                        "output": [
                            {
                                "name": "result",
                                "value": "out.c-main.next-order"
                            }
                        ]
                    },
                    "parameters": {
                        "values": [
                            {
                                "name": "minimum-orders",
                                "value": "10"
                            },
                            {
                                "name": "period",
                                "value": "12"
                            }
                        ],
                        "script": null
                    }
                } 
            }

+ Response 202 (application/json)

        {
            "id": "67121676",
            "url": "https://syrup.keboola.com/queue/job/67121676",
            "status": "waiting"
        }

## Run an stored configuration [/{image}/run]

Run a previously stored configuration.

+ Parameters
    + image (string) ... ID of the image
    
### Create a job [POST]
+ Request (application/json)
    + Headers
    
            X-StorageApi-Token: 123456

    + Body
    
            {
                "config": "next-order-1"
            }

+ Response 202 (application/json)

        {
            "id": "67121676",
            "url": "https://syrup.keboola.com/queue/job/67121676",
            "status": "waiting"
        }
