pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: beforeTests
    displayName: 'Before Tests'
    jobs:
      - job: prepare
        displayName: Prepare
        steps:
          - script: docker-compose build
            displayName: 'Build Image'

          - script: docker-compose run tests ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -v -n .
            displayName: 'PHP CS'

          - script: docker-compose run tests ./vendor/bin/phpstan
            displayName: 'PHPStan'

  - stage: Tests
    dependsOn: beforeTests
    jobs:
      - job: baseTests
        displayName: 'Base Tests'
        steps:
          - script: |
              docker-compose run tests ./vendor/bin/phpunit --testsuite base-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: containerTests
        displayName: 'Container Tests'
        pool:
          name: 'Default'
        steps:
          - script: |
              ip -4 addr show
              docker-compose run host-tests ./vendor/bin/phpunit --testsuite container-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: runnerTests
        displayName: 'Runner Tests'
        timeoutInMinutes: 100
        steps:
          - script: |
              docker-compose build --pull
              docker-compose run tests ./vendor/bin/phpunit --testsuite runner-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)
              STORAGE_API_TOKEN_FEATURE_NATIVE_TYPES: $(STORAGE_API_TOKEN_FEATURE_NATIVE_TYPES)

      - job: runnerTestsPart2
        displayName: 'Runner Tests Part 2'
        pool:
          name: 'Default'
        steps:
          - script: |
              docker-compose build --pull
              docker-compose run tests /code/phpunit.sh runner-tests-2
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: s3Tests
        displayName: 'S3 Tests'
        steps:
          - script: |
              docker-compose run tests ./vendor/bin/phpunit --testsuite s3-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: absTests
        displayName: 'ABS Tests'
        steps:
          - script: |
              docker-compose run tests ./vendor/bin/phpunit --testsuite abs-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: gcsTests
        displayName: 'GCS Tests'
        steps:
          - script: |
              docker-compose run -e STORAGE_API_URL=$STORAGE_API_URL_CONTROL_PLANE tests ./vendor/bin/phpunit --testsuite gcs-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN_CONTROL_PLANE)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)
              STORAGE_API_TOKEN_CONTROL_PLANE: $(STORAGE_API_TOKEN_CONTROL_PLANE)

      - job: synapseTests
        displayName: 'Synapse Tests'
        condition: eq(variables.RUN_SYNAPSE_TESTS, '1')
        steps:
          - script: |
              docker-compose run -e STORAGE_API_URL=$STORAGE_API_URL_SYNAPSE tests ./vendor/bin/phpunit --testsuite synapse-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: exasolTests
        displayName: 'Exasol Tests'
        condition: eq(variables.RUN_EXASOL_TESTS, '1')
        steps:
          - script: |
              docker-compose run -e STORAGE_API_URL=$STORAGE_API_URL_EXASOL tests ./vendor/bin/phpunit --testsuite exasol-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN_EXASOL)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: redshiftTests
        displayName: 'Redshift Tests'
        steps:
          - script: |
              docker-compose run tests ./vendor/bin/phpunit --testsuite redshift-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_SYNAPSE: $(STORAGE_API_TOKEN_SYNAPSE)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: teradataTests
        displayName: 'Teradata Tests'
        condition: eq(variables.RUN_TERADATA_TESTS, '1')
        steps:
          - script: |
              docker-compose run -e STORAGE_API_URL=$STORAGE_API_URL_TERADATA tests ./vendor/bin/phpunit --testsuite teradata-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN_TERADATA)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)

      - job: bigqueryTests
        displayName: 'BiqQuery Tests'
        condition: eq(variables.RUN_BIGQUERY_TESTS, '1')
        steps:
          - script: |
              docker-compose run -e STORAGE_API_URL=$STORAGE_API_URL_BIGQUERY tests ./vendor/bin/phpunit --testsuite bigquery-tests --debug
            env:
              AWS_ECR_SECRET_ACCESS_KEY: $(AWS_ECR_SECRET_ACCESS_KEY)
              DOCKERHUB_PRIVATE_PASSWORD: $(DOCKERHUB_PRIVATE_PASSWORD)
              GIT_PRIVATE_PASSWORD: $(GIT_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_PASSWORD: $(QUAYIO_PRIVATE_PASSWORD)
              QUAYIO_PRIVATE_USERNAME: $(QUAYIO_PRIVATE_USERNAME)
              STORAGE_API_TOKEN: $(STORAGE_API_TOKEN_BIGQUERY)
              STORAGE_API_TOKEN_ABS: $(STORAGE_API_TOKEN_ABS)
              STORAGE_API_TOKEN_MASTER: $(STORAGE_API_TOKEN_MASTER)
              STORAGE_API_TOKEN_READ_ONLY: $(STORAGE_API_TOKEN_READ_ONLY)
