version: '3'
# for development purposes only

services:
  tests: &tests
    build:
      context: .
      dockerfile: DockerfileTests
    image: keboola/docker-bundle-tests
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/:/tmp/
    environment:
      - AWS_ECR_ACCESS_KEY_ID
      - AWS_ECR_REGISTRY_ACCOUNT_ID
      - AWS_ECR_REGISTRY_REGION
      - AWS_ECR_REGISTRY_URI
      - AWS_ECR_SECRET_ACCESS_KEY
      - AWS_KMS_TEST_KEY
      - DOCKERHUB_PRIVATE_PASSWORD
      - DOCKERHUB_PRIVATE_SERVER
      - DOCKERHUB_PRIVATE_USERNAME
      - STORAGE_API_TOKEN
      - STORAGE_API_URL
      - STORAGE_API_TOKEN_MASTER
      - RUNNER_COMMAND_TO_GET_HOST_IP
      - STORAGE_API_TOKEN_READ_ONLY
      - STORAGE_API_TOKEN_NETWORK_POLICY
      - STORAGE_API_TOKEN_FEATURE_NATIVE_TYPES
      - STORAGE_API_TOKEN_FEATURE_NEW_NATIVE_TYPES
      - RUNNER_MIN_LOG_PORT
      - RUNNER_MAX_LOG_PORT

  host-tests:
    <<: *tests
    network_mode: host

  dev:
    <<: *tests
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  local-tests:
    <<: *tests
    ports:
      - "22:22"
    volumes:
      - .:/code/
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/:/tmp/
