imports:
    - { resource: config.yml }

monolog:
    channels: ["fooBar"]    
    handlers:
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: EMERGENCY
        syrup_stdout:
            type: stream
            path: "php://stdout"
            level: debug
            channels: ["!request", "!event", "!doctrine"]
            formatter: syrup.monolog.formatter
        storage_api:
            type: service
            id: syrup.monolog.sapi_handler
            ident: %app_name%
            level: info
            channels: ["!request", "!event", "!doctrine", "!php"]
