keboola_docker_encrypt:
    path:     /encrypt
    defaults: { _controller: KeboolaDockerBundle:Public:encrypt }
    methods:  [POST]

keboola_docker_migrate_config:
    path:     /migrate
    defaults:
      _controller: KeboolaDockerBundle:Api:migrateConfig
    methods:  [POST]

keboola_docker_component_debug:
    path:     /{component}/debug
    defaults: { _controller: KeboolaDockerBundle:Api:debug }
    methods:  [POST]

keboola_docker_component_run:
    path:     /{component}/run
    defaults: { _controller: KeboolaDockerBundle:Api:run }
    methods:  [POST]

keboola_docker_component_tag_run:
    path:     /{component}/run/tag/{tag}
    defaults: { _controller: KeboolaDockerBundle:Api:runTag }
    methods:  [POST]

keboola_docker_component_branch_debug:
    path:     /branch/{branch}/{component}/debug
    defaults: { _controller: KeboolaDockerBundle:Api:debugBranch }
    methods:  [POST]

keboola_docker_component_branch_run:
    path:     /branch/{branch}/{component}/run
    defaults: { _controller: KeboolaDockerBundle:Api:runBranch }
    methods:  [POST]

keboola_docker_component_branch_tag_run:
    path:     /branch/{branch}/{component}/run/tag/{tag}
    defaults: { _controller: KeboolaDockerBundle:Api:runBranchTag }
    methods:  [POST]

# override default syrup action run
keboola_docker_disabled_run:
    path:     /run
    defaults: { _controller: KeboolaDockerBundle:Api:disabled }
    methods:  [POST]

# run sync actions
keboola_docker_sync_action:
    path:     /{component}/action/{action}
    defaults:
      _controller: KeboolaDockerBundle:Action:process
    methods:  [POST]

keboola_docker_component_branch_sync_action:
    path:     /branch/{branch}/{component}/action/{action}
    defaults:
      _controller: KeboolaDockerBundle:Action:process
    methods:  [POST]

keboola_docker_project_stats:
    path:     /stats/project
    defaults:
        _controller: KeboolaDockerBundle:Api:projectStats
    methods:  [GET]

keboola_docker_project_stats_agg:
    path:     /stats/project/daily
    defaults:
        _controller: KeboolaDockerBundle:Api:projectDailyStats
    methods:  [GET]

keboola_docker_configuration_resolve:
    path:     /configuration/resolve
    defaults:
        _controller: KeboolaDockerBundle:Api:configurationResolve
    methods:  [POST]

keboola_docker_branc_configuration_resolve:
    path:     /branch/{branch}/configuration/resolve
    defaults:
        _controller: KeboolaDockerBundle:Api:configurationResolve
    methods:  [POST]
